[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["curl -LsSf https://astral.sh/uv/install.sh | sh", "~/.local/bin/uv sync"]

[start]
cmd = "SERVE_HTTPS=true ~/.local/bin/uv run main.py"
